### ISSUE TITLE
Installing on a Ubuntu VPS other than AppEngine.

### ISSUE THREAD

**Issue by chinmoyden** [bslatkin/mirrorrr#10]
Is it possible to run mirrorrr on a Ubuntu vps? I don't  want to use GAE. I could really use some help with it. Thanks.

**Comment by asteinbr** [comment]
Maybe you can try to use Ubuntu with typhoonae, which is a reimplementation of Google AppEngine.
https://code.google.com/p/typhoonae/

**Comment by bslatkin** [comment]
Right. There's no way to use this out of the box outside of App Engine.
