### ISSUE TITLE
Can I redirect all web requests through this server?

### ISSUE THREAD

**Issue by debnathsinha** [bslatkin/mirrorrr#12]
I'm trying to set up the proxy server in Chrome (also in Android), where every web request should be first sent to the proxy server, which then decides whether to send the original page or a page optimized for faster mobile downloads. If I go to https://mirrorrr.appspot.com/techcrunch.com the page loads, but if I set the Chrome proxy server settings to https://mirrorrr.appspot.com, and then go to techcrunch.com, then no webpage loads. 

How can I get every single web page to redirect to https://mirrorrr.appspot.com  (eventually my app domain), so I can take action on my server and send a more optimized page (compression etc)?

Thanks!

**Comment by bslatkin** [comment]
You can't do this with mirrorrr because it doesn't actually support the HTTP proxy protocol.
