### ISSUE TITLE
HOW TO run dedicated SSL Proxy?

### ISSUE THREAD

**Issue by iosoft** [bslatkin/mirrorrr#6]
Hello,

Your app is great. I love it.

My requirement is little different.
I want to use it as my dedicated SSL Proxy for my own website.
I want http://my-ssl.appspot.com will be always SSL site of my website http://my-site.com

How to do this ?

**Comment by bslatkin** [comment]
That's not a use-case that this codebase can support easily. I'd suggest checking out Cloudflare.
